var lang = {
    transactions:{
        grid_transactions_id: "Transactions Id",
        grid_payer_id: "Buyer PayPal Account",
        grid_txn_id: "Reference Number",
        grid_transactions_time: "Payment Time",
        grid_status: "Status",
        grid_amount: "Amount",
        search_result: "Transactions Inquiry Results",
        task_button_tooltip: "<b>Transactions Inquiry Results</b><br />Transactions Inquiry Results List",
        search_transactions: "Search Transactions",
        form_transactions_id: "Transactions Id",
        form_orders_id: "Orders Id",
        form_payee_id: "Payee Account",
        form_status: "Payment Status",
        form_txn_id: "Reference Number",
        form_payer_id: "Account",
        form_payer_email: "Email",
        form_payer_address: "Address",
        form_payment_date: "Payment Date",
        form_start: "Start",
        form_end: "End",
        form_created_date: "Created Date",
        form_modified_date: "Modified Date",
        submit: "Submit Query",
        close: "Close",
        create_transactions: "Create Transactions",
        transactions_status_json : {"P": "Completed", "R": "Refunded", "V": "Reversed", "C": "Canceled Reversal", "X": "Canceled"},
        transactions_status : [["P","Completed"],["R","Refunded"],["V","Reversed"],["C","Canceled Reversal"],["X","Canceled"]],
        currency: [['USD','USD'],['EUR','EUR'],['GBP','GBP'],['AUD','AUD'],['RMB','RMB'],['CAD','CAD']]
    }
}
