var lang = {
    orders:{
        grid_orders_id_header : "Orders Id",
        grid_seller_id_header : "Seller",
        grid_buyer_id_header: "Buyer",
        grid_grand_total_header: "Cost",
        grid_amount_pay_header: "Paid",
        grid_status_header: "Status",
        //----------------------------
        search_result: "Orders Inquiry Results",
        task_button_tooltip: "<b>Orders Inquiry Results</b><br />Orders Inquiry Results List",
        search_orders: "Search Orders",
        submit: "Submit Query",
        create_orders: "Create Orders",
        close_windows: "Close",
        //----------------------------
        form_orders_id: "Orders Id",
        form_created: "Created:",
        form_modified: "Modified:",
        form_seller_id: "Sales Account",
        form_ebay_address_title: "eBay Address Info",
        form_ebay_name: "Account",
        form_ebay_email: "Email",
        form_ebay_address1: "Address 1",
        form_ebay_address2: "Address 2",
        form_ebay_city: "City",
        form_ebay_state: "State/Province",
        form_ebay_postal: "Postal Code",
        form_ebay_country: "County",
        form_ebay_phone: "Phone",
        form_paypal_address_title: "PayPal Address Info",
        form_paypal_name: "Account",
        form_paypal_email: "Email",
        form_paypal_address1: "Address 1",
        form_paypal_address2: "Address 2",
        form_paypal_city: "City",
        form_paypal_state: "State/Province",
        form_paypal_postal: "Postal Code",
        form_paypal_country: "County",
        form_paypal_phone: "Phone",
        form_status: "Status",
        form_shipping_method: "Shipping Method",
        form_remarks: "Remarks",
        form_shipping_title: "Shipping",
        form_insurance_title: "Insurance",
        form_discount_title: "Discount",
        form_total_title: "Total",
        form_currency: "Currency",
        form_fee: "Fee",
        form_remarks: "Remarks",
        form_buyer_id: "Buyer Id",
        form_buyer_id: "Buyer Id",
        form_buyer_name: "Buyer Name",
        form_buyer_email: "Buyer Email",
        form_buyer_address: "Buyer Address",
        form_created_date: "Created Date",
        form_start: "Start",
        form_end: "End",
        form_modified_date: "Modified Date",
        orders_status_json: {"W": "Incomplete Checkout", "C": "Excess Payment", "V": "Investigate", "S": "Insufficient Payment", "P": "Completed Payment", "X": "Canceled"},
        orders_status: [["W", "Incomplete Checkout"], ["C", "Excess Payment"], ["V", "Investigate"], ["S", "Insufficient Payment"], ["P", "Completed Payment"], ["X", "Canceled"]],
        transactions_status: [['P','Completed'],['R','Refunded'],['V','Reversed'],['C','Canceled Reversal'],['X','Canceled']],
        currency: [['USD','USD'],['EUR','EUR'],['GBP','GBP'],['AUD','AUD'],['RMB','RMB'],['CAD','CAD']],
        shipping_method: [['B','Bulk'], ['S','SpeedPost'], ['U','UPS']]
    }
};
